server:
  servlet:
    context-path: /api/loan-service
  port: 8085

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/loan_service?useUnicode=true&characterEncoding=utf-8&createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: postgres
    password: 1234
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  jackson:
    default-property-inclusion: NON_NULL

jwt-token:
  secret: VkXp2s5v8yBEHMbQeThWmZq3t6w9zC&FJNcRfUjXn2r5u7x
  time-to-live: 3600 # 1 hour
